spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: drogbacuty@gmail.com
    password: wjqhsaoal22@@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


subscribe:
  message:
    text1: 1
    text2: 22
    text3: 33
