server:
  port: 8080

spring:
  profiles:
    active: local
    include: oauth
  h2:
    console:
      enabled: true
      path: /test_db
  datasource:
    hikari:
      #jdbc-url: org.h2.Driver
      driver-class-name: org.h2.Driver
      username: test
      password: 1234
  jpa:
    show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope: email , profileImagePath

## logging ##
logging:
  config: classpath:log4j2.xml

## jwt ##
jwt:
  secret_key: drogbalog_secret_key
  token_valid_time: 1800000
  refreshToken_valid_time: 1800000
